### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by MikeTaylor** [folio-org/mod-ldp#18]
We need unit tests that report coverage statistics.

The functionality that needs testing is described (at the WSAPI level) in [_Library Data Platform API_](https://s3.amazonaws.com/foliodocs/api/mod-ldp/ldp.html)

There are two fairly trivial calls to obtain information about the underlying database's schemas, tables and columns, and one call for searching. This is the only really interesting part of the module.
* [The source-code](https://github.com/library-data-platform/mod-ldp/blob/master/src/main/java/org/folio/ldp/QueryController.java) is pretty short.
* It transforms JSON-structured queries into SQL. See [the JSON schema for queries](https://github.com/library-data-platform/mod-ldp/blob/master/ramls/query-schema.json) and [an example query](https://github.com/library-data-platform/mod-ldp/blob/master/ramls/examples/query-example.json).

Testing these calls may involve mocking a back-end database. But much can be achieved just by testing the query translation. I will provide some example queries.

**Comment by MikeTaylor** [comment]
@kurtnordstrom I assume there is corresponding Jira to this?

**Comment by nassibnassar** [comment]
Moved to https://issues.folio.org/browse/MODLDP-21
